import Head from "next/head";
import { useState } from "react";
import Card from "../comps/Card";
import Input from "../comps/Input";
import Thanks from "../comps/Thanks";

const Home = () => {
  const [name, setName] = useState("Jane Appleseed");
  const [number, setNumber] = useState("0000 0000 0000 0000");
  const [cvc, setCVC] = useState("000");
  const [month, setMonth] = useState("00");
  const [year, setYear] = useState("00");
  const [thanks, setThanks] = useState(false);

  return (
    <>
      <Head>
        <title>Frontend Mentor | Interactive Card Details Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Card number={number} name={name} date={`${month}/${year}`} cvc={cvc} />
      <Input
        changeName={(e) => setName(e)}
        changeNumber={(e) => setNumber(e)}
        changeCVC={(e) => setCVC(e)}
        changeMonth={(e) => setMonth(e)}
        changeYear={(e) => setYear(e)}
        confirm={() => setThanks(!thanks)}
        show={thanks}
      />
      <Thanks continue={() => setThanks(!thanks)} show={thanks} />
    </>
  );
};

export default Home;
